#!/usr/bin/python3
#SPDX-FileCopyrightText:2022 Masaki Mitani
#SPDX-License Identifier;BSD-3-Clause
import sys

ans = 0.0
for line in sys.stdin:
    ans += float(line)

ans *= 2
print(ans)

ans += 10
print('一つ目の結果に+10をして→', ans)
