#!/usr/bin/python3
#SPDX-FileCopyrightText:2022 Masaki Mitani
#SPDX-License Identifier;BSD-3-Clause
import sys

a = 1.0
b = 1.0
ans = 0.0
count = 0.0

for line in sys.stdin:
    ans += float(line)
    a *= float(line)
    b /= float(line)

for i in range(1, int(ans)+1):
    if(ans % i == 0):
        count += 1

#print(count)

if(ans % 2.0 == 0.0):
    if(count == 2):
        print("和："+str(ans)+" >>>偶数 >>>素数")
    else:
        print("和："+str(ans)+" >>>偶数")
elif(count == 2):
    print("和："+str(ans)+" >>>奇数 >>>素数")
else:
    print("和："+str(ans)+" >>>奇数")

#if(a % 2.0 == 0.0):
    #print("積："+str(a)+" >>>偶数")
#else:
    #print("積："+str(a)+" >>>奇数")

#if(b % 2.0 == 0.0):
    #print("乗："+'{:.5f}'.format(b)+" >>>偶数")
#else:
    #print("乗："+'{:.5f}'.format(b)+" >>>奇数")

#print("和+積+乗："+str(ans+a+b))
